// <auto-generated />
// 生成物。手で編集した分は各行のコメントに理由を書いてある。
// 生成元: TalentStageTable / TalentTreeTable / TalentTable / SkillTable
using Zproto;

using static StarResonanceDps.Core.CombatRuntime.DataTypes.Enums.Professions;

namespace StarResonanceDps.Core.CombatRuntime.DataTypes;

/// <summary>
/// 特化を通信から特定するためのテーブル。
///
/// <para>
/// 特化アビリティの根ノード(<c>TalentStageTable.RootId</c>)の効果は2種類しかない:
///   <c>[3, マーカーバフ, 1]</c> … 18特化すべてが持つ
///   <c>[6, 置換元, 置換先]</c>   … 9特化だけが持つ
/// </para>
///
/// <para>
/// <b>判定に使うのは2つ。</b> 置換後スキルID(置換する9特化＋光砕の2450)と、
/// タレント由来のバフID(全18特化)。
/// </para>
///
/// <para>
/// バフ側は <b>FightSourceType == 6 (EFightSourceTalent) かつ 術者＝保持者</b> のものだけを採る。
/// 味方に配られる効果バフ(威咲 2202112 など)は srcType=1/0 で届くため落ちる。
/// 実測 2026-08-27: srcType=6 は182件すべて術者＝保持者、例外0件。
/// </para>
///
/// <para>
/// バフ表は距離0(特化アビリティ本体＝マーカー)と距離1以上(ツリー)を同じ表に持つ。
/// マーカーは AOI出現スナップショットやマップロードで全プレイヤーぶん届くので、
/// 他人の特化はそこで確定する。ツリーバフはタレントを振っている人にだけ乗る。
/// </para>
///
/// <para>
/// <b>このテーブルで Rank1(未装着)は判定しない。</b> どちらも「あること」しか示さないため、
/// 何も観測できないのは「まだ観測していない」でしかない。
/// </para>
/// </summary>
public static class SpecDetectionTables
{
    /// <summary>
    /// 置換後スキルID → 特化。置換する9特化ぶん。
    /// 出所は根ノードの <c>TalentEffect [6, 置換元, 置換先]</c>。
    /// </summary>
    public static SubProfessionId GetSubProfessionIdByReplacedSkillId(int skillId) => skillId switch
    {
        1930   => SubProfessionId.SubProfession_Block,             // 剛守  1922 Shield Bash → 1930 Countercrush
        2307   => SubProfessionId.SubProfession_Concerto,          // 響奏  2306 Amplified Beat → 2307 Healing Beat
        2301   => SubProfessionId.SubProfession_Concerto,          // 響奏  2321 String Strike → 2301 Resonant Strings
        1606   => SubProfessionId.SubProfession_CrimsonExpertise,  // 炎舞  1605 Blazing Ascension → 1606 Frenzied Slash
        2222   => SubProfessionId.SubProfession_Falconry,          // 鷹弓  2220 Storm Arrow → 2222 Double Arrow
        1241   => SubProfessionId.SubProfession_Frostbeam,         // 霜天  1242 Frost Lance → 1241 Frostbeam
        1507   => SubProfessionId.SubProfession_Lifebind,          // 森癒  1518 Wild Bloom → 1507 Life Bloom
        1715   => SubProfessionId.SubProfession_Moonstrike,        // 月影  1714 Iaido Slash → 1715 Moonstrike
        2406   => SubProfessionId.SubProfession_Shield,            // 光盾  2405 Valor Bash → 2406 Vanguard Strike
        1419   => SubProfessionId.SubProfession_Skyward,           // 乱風  1418 Gale Thrust → 1419 Skyfall
        2450   => SubProfessionId.SubProfession_Recovery,          // 光砕  2405 Valor Bash に随伴する 场地标记01
        _ => SubProfessionId.SubProfession_Unknown
    };

    /// <summary>
    /// タレント由来バフID → (特化, 根ノードからの距離)。<b>全18特化</b>ぶん、計 463 件。
    /// そのツリーだけが付与するバフに限っていて、他の26ツリーとは1件も重ならない。
    /// 距離0 = 特化アビリティ本体(マーカー)、距離1以上 = ツリーの他ノード。
    ///
    /// <para>
    /// <b>キーは「ノードが付与するバフID」で、線を流れてくるIDそのものではない。</b>
    /// 実測では付与バフID(末尾0)は一度も現れず、届いたのは <c>+1</c> <c>+2</c> の実行時変種だった。
    /// 引くときは <see cref="TryResolveSpecTalentBuff"/> を使い、観測IDを10刻みに丸めること。
    /// </para>
    /// </summary>
    private static (SubProfessionId Spec, int DistanceFromRoot) LookupGrantedTreeBuff(int grantedBuffId) => grantedBuffId switch
    {
        2200070  => (SubProfessionId.SubProfession_Iaido,              2), // 雷刃  根から2 node=5212  居合天授
        2200080  => (SubProfessionId.SubProfession_Iaido,              5), // 雷刃  根から5 node=141002  追击风袭
        2200090  => (SubProfessionId.SubProfession_Iaido,              3), // 雷刃  根から3 node=148003  禅瞬之机
        2200110  => (SubProfessionId.SubProfession_Iaido,              8), // 雷刃  根から8 node=147002  雷返
        2200120  => (SubProfessionId.SubProfession_Iaido,              9), // 雷刃  根から9 node=5597  拔刀真空波
        2200130  => (SubProfessionId.SubProfession_Moonstrike,         8), // 月影  根から8 node=128028  幸运强效
        2200140  => (SubProfessionId.SubProfession_Iaido,              2), // 雷刃  根から2 node=8470  一闪狂刃
        2200150  => (SubProfessionId.SubProfession_Iaido,             11), // 雷刃  根から11 node=113018  刃风界域
        2200160  => (SubProfessionId.SubProfession_Moonstrike,         3), // 月影  根から3 node=157001  雷魂之触
        2200170  => (SubProfessionId.SubProfession_Moonstrike,        11), // 月影  根から11 node=121011  幸运雷印
        2200180  => (SubProfessionId.SubProfession_Moonstrike,         6), // 月影  根から6 node=5608  镰刀分裂
        2200200  => (SubProfessionId.SubProfession_Moonstrike,         7), // 月影  根から7 node=118011  幻镰之境
        2200210  => (SubProfessionId.SubProfession_Moonstrike,        12), // 月影  根から12 node=119011  月刃疾袭
        2200220  => (SubProfessionId.SubProfession_Moonstrike,         8), // 月影  根から8 node=160001  雷电之力
        2200230  => (SubProfessionId.SubProfession_Moonstrike,         2), // 月影  根から2 node=7240  月影时延
        2200240  => (SubProfessionId.SubProfession_Moonstrike,        11), // 月影  根から11 node=116013  霹雳之光
        2200260  => (SubProfessionId.SubProfession_Moonstrike,         8), // 月影  根から8 node=161001  决斗意识
        2200300  => (SubProfessionId.SubProfession_Iaido,              8), // 雷刃  根から8 node=145002  绝地反击
        2200320  => (SubProfessionId.SubProfession_Iaido,              0), // 雷刃  根から0 node=130003  真雷居合
        2200330  => (SubProfessionId.SubProfession_Moonstrike,         2), // 月影  根から2 node=6305  幻影镰刀
        2200340  => (SubProfessionId.SubProfession_Iaido,              7), // 雷刃  根から7 node=132003  锐击传承
        2200350  => (SubProfessionId.SubProfession_Iaido,              5), // 雷刃  根から5 node=8467  雷印增益
        2200360  => (SubProfessionId.SubProfession_Iaido,              6), // 雷刃  根から6 node=134026  终极奥义
        2200410  => (SubProfessionId.SubProfession_Iaido,              8), // 雷刃  根から8 node=8468  无穷雷霆
        2200420  => (SubProfessionId.SubProfession_Iaido,              7), // 雷刃  根から7 node=109017  雷印回溯
        2200430  => (SubProfessionId.SubProfession_Iaido,              4), // 雷刃  根から4 node=139002  超频压制
        2200440  => (SubProfessionId.SubProfession_Iaido,              7), // 雷刃  根から7 node=133002  无双飞雷神
        2200450  => (SubProfessionId.SubProfession_Iaido,              6), // 雷刃  根から6 node=5596  暴斩
        2200460  => (SubProfessionId.SubProfession_Iaido,              5), // 雷刃  根から5 node=154001  追击风袭
        2200470  => (SubProfessionId.SubProfession_Iaido,             11), // 雷刃  根から11 node=106018  刀意双绝
        2200480  => (SubProfessionId.SubProfession_Iaido,              2), // 雷刃  根から2 node=146002  雷印亲和
        2200490  => (SubProfessionId.SubProfession_Iaido,             12), // 雷刃  根から12 node=110019  雷压倍增
        2200510  => (SubProfessionId.SubProfession_Iaido,              6), // 雷刃  根から6 node=5593  刀意·极
        2200520  => (SubProfessionId.SubProfession_Iaido,              8), // 雷刃  根から8 node=5208  霹雳符印
        2200530  => (SubProfessionId.SubProfession_Iaido,              8), // 雷刃  根から8 node=128029  破斩
        2200540  => (SubProfessionId.SubProfession_Iaido,              8), // 雷刃  根から8 node=149003  暴裂
        2200550  => (SubProfessionId.SubProfession_Iaido,              5), // 雷刃  根から5 node=5210  瞬斩
        2200560  => (SubProfessionId.SubProfession_Iaido,              8), // 雷刃  根から8 node=152001  精进
        2200570  => (SubProfessionId.SubProfession_Moonstrike,         5), // 月影  根から5 node=6307  雷霆之镰精进
        2200580  => (SubProfessionId.SubProfession_Moonstrike,         8), // 月影  根から8 node=7244  刀意回复
        2200590  => (SubProfessionId.SubProfession_Moonstrike,         0), // 月影  根から0 node=131002  神影月刃
        2200600  => (SubProfessionId.SubProfession_Moonstrike,         9), // 月影  根から9 node=5606  神罚镰刃
        2200610  => (SubProfessionId.SubProfession_Moonstrike,         5), // 月影  根から5 node=7242  月刃电荷之种
        2200620  => (SubProfessionId.SubProfession_Moonstrike,         7), // 月影  根から7 node=120012  刀意·极
        2200630  => (SubProfessionId.SubProfession_Moonstrike,         6), // 月影  根から6 node=5604  雷鸣千闪
        2200640  => (SubProfessionId.SubProfession_Moonstrike,         4), // 月影  根から4 node=162001  绚影层叠
        2200650  => (SubProfessionId.SubProfession_Moonstrike,         8), // 月影  根から8 node=163001  雷击强化
        2200660  => (SubProfessionId.SubProfession_Moonstrike,         8), // 月影  根から8 node=165001  电荷捕手
        2200670  => (SubProfessionId.SubProfession_Moonstrike,         5), // 月影  根から5 node=167001  雷击强化
        2200680  => (SubProfessionId.SubProfession_Moonstrike,         7), // 月影  根から7 node=115012  月影锐击
        2200690  => (SubProfessionId.SubProfession_Moonstrike,         8), // 月影  根から8 node=124029  霹雳符印
        2200700  => (SubProfessionId.SubProfession_Moonstrike,         2), // 月影  根から2 node=166001  雷符刀意
        2200710  => (SubProfessionId.SubProfession_Moonstrike,         8), // 月影  根から8 node=6309  霹雳电荷
        2200720  => (SubProfessionId.SubProfession_Moonstrike,         5), // 月影  根から5 node=169001  月刃神速
        2200730  => (SubProfessionId.SubProfession_Moonstrike,         6), // 月影  根から6 node=134027  雷霆神威
        2200740  => (SubProfessionId.SubProfession_Iaido,              8), // 雷刃  根から8 node=124028  雷霆神威
        2201010  => (SubProfessionId.SubProfession_Block,             12), // 剛守  根から12 node=963001  砂岩之握精进
        2201080  => (SubProfessionId.SubProfession_Block,              8), // 剛守  根から8 node=906012  格挡回复
        2201090  => (SubProfessionId.SubProfession_Block,              8), // 剛守  根から8 node=923013  格挡反击
        2201150  => (SubProfessionId.SubProfession_Block,              8), // 剛守  根から8 node=962001  幸运壁垒
        2201160  => (SubProfessionId.SubProfession_Earthfort,         13), // 剛身  根から13 node=948001  猛击庇护
        2201170  => (SubProfessionId.SubProfession_Earthfort,         13), // 剛身  根から13 node=918007  护盾回能
        2201180  => (SubProfessionId.SubProfession_Earthfort,         14), // 剛身  根から14 node=917007  猛击援护
        2201190  => (SubProfessionId.SubProfession_Earthfort,         14), // 剛身  根から14 node=916007  猛击加持
        2201200  => (SubProfessionId.SubProfession_Earthfort,         10), // 剛身  根から10 node=6071  护盾连击
        2201210  => (SubProfessionId.SubProfession_Earthfort,          6), // 剛身  根から6 node=921007  巨岩之息
        2201220  => (SubProfessionId.SubProfession_Earthfort,          5), // 剛身  根から5 node=951001  全能效益
        2201240  => (SubProfessionId.SubProfession_Earthfort,          6), // 剛身  根から6 node=922007  护盾回声
        2201250  => (SubProfessionId.SubProfession_Block,              8), // 剛守  根から8 node=959001  魔法盾域
        2201320  => (SubProfessionId.SubProfession_Block,              0), // 剛守  根から0 node=930006  撼地打击
        2201330  => (SubProfessionId.SubProfession_Earthfort,          0), // 剛身  根から0 node=931006  护盾打击
        2201350  => (SubProfessionId.SubProfession_Block,             13), // 剛守  根から13 node=933004  砂岩回溯
        2201360  => (SubProfessionId.SubProfession_Block,             12), // 剛守  根から12 node=934004  幸缘维护
        2201370  => (SubProfessionId.SubProfession_Block,              9), // 剛守  根から9 node=932007  格挡光环
        2201420  => (SubProfessionId.SubProfession_Earthfort,          8), // 剛身  根から8 node=6066  激怒扩充
        2201430  => (SubProfessionId.SubProfession_Earthfort,         10), // 剛身  根から10 node=6068  怒爆精进
        2201440  => (SubProfessionId.SubProfession_Earthfort,          3), // 剛身  根から3 node=942001  星之狂怒
        2201450  => (SubProfessionId.SubProfession_Earthfort,          8), // 剛身  根から8 node=6067  石域
        2201460  => (SubProfessionId.SubProfession_Earthfort,          3), // 剛身  根から3 node=944001  岩盾倍增
        2201470  => (SubProfessionId.SubProfession_Earthfort,         13), // 剛身  根から13 node=945001  巨石护体
        2201480  => (SubProfessionId.SubProfession_Earthfort,          6), // 剛身  根から6 node=946001  猛击强化
        2201490  => (SubProfessionId.SubProfession_Earthfort,         14), // 剛身  根から14 node=941001  回复
        2201500  => (SubProfessionId.SubProfession_Earthfort,          3), // 剛身  根から3 node=914007  碎星崩裂
        2201510  => (SubProfessionId.SubProfession_Earthfort,         11), // 剛身  根から11 node=1488  岩之主
        2201520  => (SubProfessionId.SubProfession_Earthfort,          5), // 剛身  根から5 node=950001  碎击
        2201530  => (SubProfessionId.SubProfession_Earthfort,         12), // 剛身  根から12 node=920007  护盾强度
        2201540  => (SubProfessionId.SubProfession_Earthfort,         14), // 剛身  根から14 node=940001  护盾猛击追击
        2201550  => (SubProfessionId.SubProfession_Earthfort,          6), // 剛身  根から6 node=943001  激怒岩之主
        2201560  => (SubProfessionId.SubProfession_Earthfort,         13), // 剛身  根から13 node=954001  愈战愈勇
        2201570  => (SubProfessionId.SubProfession_Earthfort,         14), // 剛身  根から14 node=952001  岩护
        2201580  => (SubProfessionId.SubProfession_Block,              3), // 剛守  根から3 node=956001  壁垒怒火
        2201590  => (SubProfessionId.SubProfession_Block,              7), // 剛守  根から7 node=964001  格挡庇护
        2201600  => (SubProfessionId.SubProfession_Block,              7), // 剛守  根から7 node=958001  魔法格挡
        // 2201610 は 2026-09-05 に除外していたが、2026-09-11 に復活させた。
        // 丸めで同じ扱いになる 2201612「岩属性強化」が剛守・剛身の両方から出るのが除外の理由だったが、
        // TryResolveSpecByParentBuff が親(2201611=剛守 / 2201511=剛身)で引き直すので取り違えない。
        // 全ログ再生で、このキーを戻しても不一致は0件のまま(検知は+125件)。
        2201610  => (SubProfessionId.SubProfession_Block,              3), // 剛守  根から3 node=907011  岩之心
        2201620  => (SubProfessionId.SubProfession_Block,              5), // 剛守  根から5 node=6064  轰拳
        2201630  => (SubProfessionId.SubProfession_Block,              7), // 剛守  根から7 node=966001  轰拳激怒
        2201640  => (SubProfessionId.SubProfession_Block,             13), // 剛守  根から13 node=913016  岩拳回复
        2201650  => (SubProfessionId.SubProfession_Block,             13), // 剛守  根から13 node=968001  壁垒刚毅
        2201660  => (SubProfessionId.SubProfession_Block,              3), // 剛守  根から3 node=957001  怒击强化
        2201670  => (SubProfessionId.SubProfession_Block,              9), // 剛守  根から9 node=6055  轰拳二连击
        2201680  => (SubProfessionId.SubProfession_Block,             13), // 剛守  根から13 node=961001  威压
        2201690  => (SubProfessionId.SubProfession_Block,             13), // 剛守  根から13 node=967001  轰拳怒岩
        2201700  => (SubProfessionId.SubProfession_Block,             11), // 剛守  根から11 node=925018  反击风暴
        2201710  => (SubProfessionId.SubProfession_Block,             12), // 剛守  根から12 node=969001  刚岩幸运
        2201720  => (SubProfessionId.SubProfession_Block,             12), // 剛守  根から12 node=970001  刚岩精通
        2201730  => (SubProfessionId.SubProfession_Block,              7), // 剛守  根から7 node=960001  反击强化
        2202080  => (SubProfessionId.SubProfession_Smite,              9), // 威咲  根から9 node=546001  元素精通
        2202100  => (SubProfessionId.SubProfession_Smite,              5), // 威咲  根から5 node=508014  狂野祝福
        2202110  => (SubProfessionId.SubProfession_Smite,              0), // 威咲  根から0 node=510012  惩击流
        2202120  => (SubProfessionId.SubProfession_Smite,              2), // 威咲  根から2 node=505013  自然护盾
        2202130  => (SubProfessionId.SubProfession_Smite,             10), // 威咲  根から10 node=523015  双重灌注
        2202140  => (SubProfessionId.SubProfession_Smite,              5), // 威咲  根から5 node=511013  幸运愈合
        2202160  => (SubProfessionId.SubProfession_Lifebind,           8), // 森癒  根から8 node=2243  战斗状态加草领域
        2202170  => (SubProfessionId.SubProfession_Lifebind,           5), // 森癒  根から5 node=515003  灵机一动
        2202180  => (SubProfessionId.SubProfession_Lifebind,           2), // 森癒  根から2 node=514003  治疗充盈
        2202200  => (SubProfessionId.SubProfession_Lifebind,          10), // 森癒  根から10 node=518003  绿意二连奏
        2202210  => (SubProfessionId.SubProfession_Lifebind,          10), // 森癒  根から10 node=567001  绿意之爆发
        2202220  => (SubProfessionId.SubProfession_Lifebind,           2), // 森癒  根から2 node=520003  生命延展
        2202230  => (SubProfessionId.SubProfession_Lifebind,           8), // 森癒  根から8 node=522004  种子恩赐
        2202240  => (SubProfessionId.SubProfession_Lifebind,           7), // 森癒  根から7 node=558001  绽放光环
        2202250  => (SubProfessionId.SubProfession_Smite,              8), // 威咲  根から8 node=2249  鹿之奔袭
        2202270  => (SubProfessionId.SubProfession_Lifebind,           9), // 森癒  根から9 node=525014  天降圣光
        2202290  => (SubProfessionId.SubProfession_Lifebind,           6), // 森癒  根から6 node=527013  生命馈赠
        2202300  => (SubProfessionId.SubProfession_Smite,              6), // 威咲  根から6 node=528017  能量归宿
        2202320  => (SubProfessionId.SubProfession_Smite,             10), // 威咲  根から10 node=524014  精通伤害
        2202340  => (SubProfessionId.SubProfession_Lifebind,           0), // 森癒  根から0 node=531002  绿意之轮回
        2202360  => (SubProfessionId.SubProfession_Smite,              4), // 威咲  根から4 node=553001  荆棘
        2202380  => (SubProfessionId.SubProfession_Smite,             10), // 威咲  根から10 node=525013  保护
        2202440  => (SubProfessionId.SubProfession_Smite,              4), // 威咲  根から4 node=512014  自然护盾吸收翻倍
        2202450  => (SubProfessionId.SubProfession_Smite,             13), // 威咲  根から13 node=545001  脉冲之息
        2202460  => (SubProfessionId.SubProfession_Smite,              7), // 威咲  根から7 node=542001  不羁之种狠狠的加伤害
        2202470  => (SubProfessionId.SubProfession_Smite,             12), // 威咲  根から12 node=543001  蓓蕾繁生
        2202480  => (SubProfessionId.SubProfession_Smite,              6), // 威咲  根から6 node=541001  广域荆棘
        2202490  => (SubProfessionId.SubProfession_Smite,              8), // 威咲  根から8 node=554001  荆棘翻倍
        2202500  => (SubProfessionId.SubProfession_Smite,              2), // 威咲  根から2 node=532003  脉冲二重
        2202510  => (SubProfessionId.SubProfession_Smite,             11), // 威咲  根から11 node=552001  庇护缩减
        2202520  => (SubProfessionId.SubProfession_Smite,              7), // 威咲  根から7 node=7303  脉冲回望
        2202530  => (SubProfessionId.SubProfession_Smite,             10), // 威咲  根から10 node=549001  迅捷蓓蕾
        2202550  => (SubProfessionId.SubProfession_Smite,              9), // 威咲  根から9 node=526016  共生延长
        2202560  => (SubProfessionId.SubProfession_Smite,              8), // 威咲  根から8 node=506014  脉动
        2202570  => (SubProfessionId.SubProfession_Smite,              4), // 威咲  根から4 node=540001  幸运伤害
        2202580  => (SubProfessionId.SubProfession_Smite,             13), // 威咲  根から13 node=548001  坍缩
        2202590  => (SubProfessionId.SubProfession_Smite,             12), // 威咲  根から12 node=555001  狂野幸运
        2202600  => (SubProfessionId.SubProfession_Lifebind,           4), // 森癒  根から4 node=556001  绿意滋养
        2202610  => (SubProfessionId.SubProfession_Lifebind,          12), // 森癒  根から12 node=557001  极意鼓舞
        2202620  => (SubProfessionId.SubProfession_Lifebind,           5), // 森癒  根から5 node=516003  生命绽放
        2202630  => (SubProfessionId.SubProfession_Lifebind,           7), // 森癒  根から7 node=5523  生机
        2202640  => (SubProfessionId.SubProfession_Lifebind,           8), // 森癒  根から8 node=560001  盛放精进
        2202650  => (SubProfessionId.SubProfession_Lifebind,           6), // 森癒  根から6 node=561001  绽放轮回
        2202660  => (SubProfessionId.SubProfession_Lifebind,           4), // 森癒  根から4 node=562001  能量勃发
        2202670  => (SubProfessionId.SubProfession_Lifebind,           4), // 森癒  根から4 node=521003  超然
        2202680  => (SubProfessionId.SubProfession_Lifebind,          13), // 森癒  根から13 node=559001  治疗冷却
        2202690  => (SubProfessionId.SubProfession_Lifebind,          13), // 森癒  根から13 node=563001  三色启示
        2202700  => (SubProfessionId.SubProfession_Lifebind,           7), // 森癒  根から7 node=40024  花株绽放
        2202710  => (SubProfessionId.SubProfession_Lifebind,          10), // 森癒  根から10 node=519003  蓓蕾生花
        2202720  => (SubProfessionId.SubProfession_Lifebind,           9), // 森癒  根から9 node=526015  鼓舞强化
        2202730  => (SubProfessionId.SubProfession_Lifebind,           9), // 森癒  根から9 node=569001  能量扩展
        2202740  => (SubProfessionId.SubProfession_Lifebind,          12), // 森癒  根から12 node=570001  救护
        2202750  => (SubProfessionId.SubProfession_Lifebind,          11), // 森癒  根から11 node=564001  绽放瞬发
        2203060  => (SubProfessionId.SubProfession_Wildpack,           6), // 狼弓  根から6 node=1106010  战吼之法
        2203070  => (SubProfessionId.SubProfession_Wildpack,           8), // 狼弓  根から8 node=1140001  魔狼之嗜
        2203090  => (SubProfessionId.SubProfession_Wildpack,           3), // 狼弓  根から3 node=1108010  幻影狼袭
        2203100  => (SubProfessionId.SubProfession_Wildpack,           3), // 狼弓  根から3 node=1109010  魔狼撕咬
        2203110  => (SubProfessionId.SubProfession_Wildpack,           9), // 狼弓  根から9 node=1110010  魔狼双生
        2203120  => (SubProfessionId.SubProfession_Wildpack,          10), // 狼弓  根から10 node=1141001  光铸学识
        2203140  => (SubProfessionId.SubProfession_Wildpack,           5), // 狼弓  根から5 node=5550  灵箭神踪
        2203150  => (SubProfessionId.SubProfession_Falconry,           3), // 鷹弓  根から3 node=1152001  光能之矢
        2203160  => (SubProfessionId.SubProfession_Falconry,           9), // 鷹弓  根から9 node=1116003  猎鹰之息
        2203170  => (SubProfessionId.SubProfession_Falconry,          10), // 鷹弓  根から10 node=1160001  光耀射手
        2203180  => (SubProfessionId.SubProfession_Falconry,           3), // 鷹弓  根から3 node=1118004  鹰眼闪电破
        2203190  => (SubProfessionId.SubProfession_Falconry,           5), // 鷹弓  根から5 node=1112011  天空之落星
        2203200  => (SubProfessionId.SubProfession_Falconry,           3), // 鷹弓  根から3 node=1115003  锐射
        2203210  => (SubProfessionId.SubProfession_Falconry,           8), // 鷹弓  根から8 node=1159001  心之鹰击
        2203220  => (SubProfessionId.SubProfession_Falconry,          10), // 鷹弓  根から10 node=1161001  暴击双生
        2203260  => (SubProfessionId.SubProfession_Wildpack,           0), // 狼弓  根から0 node=1126010  成熟之翼展
        2203290  => (SubProfessionId.SubProfession_Falconry,           0), // 鷹弓  根から0 node=1129002  苍穹之落
        2203300  => (SubProfessionId.SubProfession_Wildpack,           9), // 狼弓  根から9 node=1114005  生命流失
        2203360  => (SubProfessionId.SubProfession_Wildpack,          10), // 狼弓  根から10 node=1143001  野狼锐击
        2203370  => (SubProfessionId.SubProfession_Wildpack,           5), // 狼弓  根から5 node=1151001  野兽怒涛之力
        2203380  => (SubProfessionId.SubProfession_Wildpack,          11), // 狼弓  根から11 node=1146001  箭雨加速
        2203390  => (SubProfessionId.SubProfession_Wildpack,           6), // 狼弓  根から6 node=1124011  生命猎杀
        2203400  => (SubProfessionId.SubProfession_Wildpack,           6), // 狼弓  根から6 node=1130002  狼牙之契
        2203410  => (SubProfessionId.SubProfession_Wildpack,          10), // 狼弓  根から10 node=1138001  光影流失
        2203420  => (SubProfessionId.SubProfession_Wildpack,           5), // 狼弓  根から5 node=1112010  成长的宠物
        2203430  => (SubProfessionId.SubProfession_Wildpack,           5), // 狼弓  根から5 node=5547  传奇生物
        2203440  => (SubProfessionId.SubProfession_Wildpack,           8), // 狼弓  根から8 node=1105010  强化怒涛射击
        2203450  => (SubProfessionId.SubProfession_Wildpack,           8), // 狼弓  根から8 node=1145001  狂野呼唤冷却
        2203460  => (SubProfessionId.SubProfession_Wildpack,          10), // 狼弓  根から10 node=1139001  生命流失之精通
        2203470  => (SubProfessionId.SubProfession_Wildpack,           3), // 狼弓  根から3 node=1150001  追光锋锐
        2203480  => (SubProfessionId.SubProfession_Wildpack,          11), // 狼弓  根から11 node=1147001  追光之箭
        2203490  => (SubProfessionId.SubProfession_Wildpack,           3), // 狼弓  根から3 node=1149001  光意
        2203500  => (SubProfessionId.SubProfession_Wildpack,          10), // 狼弓  根から10 node=1142001  魔狼对残血增伤
        2203510  => (SubProfessionId.SubProfession_Wildpack,           3), // 狼弓  根から3 node=1111010  狂野呼唤践踏
        2203520  => (SubProfessionId.SubProfession_Falconry,           5), // 鷹弓  根から5 node=5561  钢制喙
        2203530  => (SubProfessionId.SubProfession_Falconry,          11), // 鷹弓  根から11 node=1166001  幻影雄鹰
        2203540  => (SubProfessionId.SubProfession_Falconry,           3), // 鷹弓  根から3 node=1165001  凝神专注
        2203550  => (SubProfessionId.SubProfession_Falconry,           8), // 鷹弓  根から8 node=1117003  双矢极意
        2203560  => (SubProfessionId.SubProfession_Falconry,          10), // 鷹弓  根から10 node=1164001  锐利二连矢
        2203570  => (SubProfessionId.SubProfession_Falconry,           3), // 鷹弓  根から3 node=1122003  光能凝滞
        2203580  => (SubProfessionId.SubProfession_Falconry,          10), // 鷹弓  根から10 node=1158001  猎鹰破式
        2203590  => (SubProfessionId.SubProfession_Falconry,           5), // 鷹弓  根から5 node=5559  鹰眼
        2203600  => (SubProfessionId.SubProfession_Falconry,           6), // 鷹弓  根から6 node=1120003  天界雄鹰
        2203610  => (SubProfessionId.SubProfession_Falconry,          11), // 鷹弓  根から11 node=1154001  光能裂隙-爆炸箭增伤
        2203620  => (SubProfessionId.SubProfession_Falconry,           6), // 鷹弓  根から6 node=1119004  闪电链
        2203630  => (SubProfessionId.SubProfession_Falconry,           5), // 鷹弓  根から5 node=1162001  闪电破
        2203640  => (SubProfessionId.SubProfession_Falconry,           6), // 鷹弓  根から6 node=1124012  聚能之力
        2203650  => (SubProfessionId.SubProfession_Falconry,           8), // 鷹弓  根から8 node=1167001  聚能射击附加钢制喙
        2203660  => (SubProfessionId.SubProfession_Falconry,           9), // 鷹弓  根から9 node=1121003  天界雄鹰不消耗钢制喙
        2203670  => (SubProfessionId.SubProfession_Falconry,          10), // 鷹弓  根から10 node=1156001  锐利二连矢
        2204060  => (SubProfessionId.SubProfession_Frostbeam,          2), // 霜天  根から2 node=206017  浪潮精通
        2204070  => (SubProfessionId.SubProfession_Frostbeam,          2), // 霜天  根から2 node=225026  冰晶共鸣
        2204090  => (SubProfessionId.SubProfession_Frostbeam,         11), // 霜天  根から11 node=207018  冰晶倍扩
        2204100  => (SubProfessionId.SubProfession_Frostbeam,          8), // 霜天  根から8 node=268001  冰凌之约
        2204110  => (SubProfessionId.SubProfession_Frostbeam,          5), // 霜天  根から5 node=211017  寒风凝聚
        2204120  => (SubProfessionId.SubProfession_Frostbeam,          0), // 霜天  根から0 node=212017  射线流
        2204140  => (SubProfessionId.SubProfession_Icicle,            11), // 氷牙  根から11 node=219011  冰霜彗星
        2204150  => (SubProfessionId.SubProfession_Icicle,             9), // 氷牙  根から9 node=249001  冻结星辰
        2204160  => (SubProfessionId.SubProfession_Icicle,             7), // 氷牙  根から7 node=247002  冰矛连弹
        2204170  => (SubProfessionId.SubProfession_Icicle,             7), // 氷牙  根から7 node=255001  风雨际会
        2204180  => (SubProfessionId.SubProfession_Icicle,             2), // 氷牙  根から2 node=222011  碎冰之击
        2204190  => (SubProfessionId.SubProfession_Icicle,            10), // 氷牙  根から10 node=221011  冰川怒潮
        2204200  => (SubProfessionId.SubProfession_Icicle,            10), // 氷牙  根から10 node=215011  极寒之矛
        2204230  => (SubProfessionId.SubProfession_Frostbeam,          6), // 霜天  根から6 node=234001  玄冰无界
        // 2204240 氷霜衝撃(Frost Shock, node=226026) は除外。丸めで同じ扱いになる 2204241 が
        // 霜天からも出るため。その出所は 2204250 急速冷凍 で、TalentTreeTable に
        // 氷牙(node=227027 wt=2/bd=0)と霜天(node=256001 wt=2/bd=1)の2ノードが実在する共有タレント。
        // どちらの特化とも言えないので判定表のキーにできず、親優先でも解けない。
        //
        // 2026-09-11 に「親が 2204250 なら帰属しない」関門を足して復活を試したが、撤去した。
        // このキーで特化が付いた97件・7人は全員ほかのバフでも氷牙と判定されており、
        // 戻しても判定できる人は1人も増えない。キーを外しておけば 2204241 はそもそも
        // 解決段階に入らないので、関門は死にコードになる(実測: 関門に届く回0)。
        // 再生成しても復活させないこと。
        2204260  => (SubProfessionId.SubProfession_Frostbeam,          7), // 霜天  根から7 node=228026  冰息宁静
        2204290  => (SubProfessionId.SubProfession_Frostbeam,          5), // 霜天  根から5 node=231003  冰光共鸣
        2204300  => (SubProfessionId.SubProfession_Icicle,             0), // 氷牙  根から0 node=233002  冰矛流
        2204320  => (SubProfessionId.SubProfession_Frostbeam,         10), // 霜天  根から10 node=235001  冰冷脉冲
        2204370  => (SubProfessionId.SubProfession_Icicle,             7), // 氷牙  根から7 node=5588  无尽苦寒
        2204380  => (SubProfessionId.SubProfession_Icicle,            14), // 氷牙  根から14 node=242002  冰矛二连发
        2204390  => (SubProfessionId.SubProfession_Icicle,             9), // 氷牙  根から9 node=241002  陨星风暴之冻结
        2204400  => (SubProfessionId.SubProfession_Icicle,             2), // 氷牙  根から2 node=2256  节能
        2204410  => (SubProfessionId.SubProfession_Icicle,             5), // 氷牙  根から5 node=216011  霜之利刃
        2204420  => (SubProfessionId.SubProfession_Icicle,             4), // 氷牙  根から4 node=217011  冰矛伤害+100% 吟唱时间+100%
        2204430  => (SubProfessionId.SubProfession_Icicle,            13), // 氷牙  根から13 node=250001  陨石数量+1
        2204440  => (SubProfessionId.SubProfession_Icicle,            12), // 氷牙  根から12 node=244001  冰矛暴击
        2204450  => (SubProfessionId.SubProfession_Icicle,            14), // 氷牙  根から14 node=251001  灌注升华
        2204460  => (SubProfessionId.SubProfession_Icicle,             5), // 氷牙  根から5 node=246002  致命冰矛
        2204470  => (SubProfessionId.SubProfession_Icicle,            12), // 氷牙  根から12 node=245001  暴击之寒
        2204480  => (SubProfessionId.SubProfession_Icicle,             8), // 氷牙  根から8 node=248001  凛冽
        2204490  => (SubProfessionId.SubProfession_Icicle,             5), // 氷牙  根から5 node=220011  锐利冰暴
        2204500  => (SubProfessionId.SubProfession_Icicle,             8), // 氷牙  根から8 node=253001  玄冰赋能
        2204510  => (SubProfessionId.SubProfession_Icicle,             9), // 氷牙  根から9 node=254001  寒霜侵袭
        2204520  => (SubProfessionId.SubProfession_Icicle,             5), // 氷牙  根から5 node=223027  幸运伤害
        2204530  => (SubProfessionId.SubProfession_Frostbeam,          2), // 霜天  根から2 node=2252  寒意留存
        2204540  => (SubProfessionId.SubProfession_Frostbeam,          5), // 霜天  根から5 node=227026  霜华启示
        2204550  => (SubProfessionId.SubProfession_Frostbeam,         13), // 霜天  根から13 node=258001  冰箭狂潮（在2204070判定）
        2204560  => (SubProfessionId.SubProfession_Frostbeam,         12), // 霜天  根から12 node=259001  冰晶之力
        2204570  => (SubProfessionId.SubProfession_Frostbeam,         12), // 霜天  根から12 node=260001  冰晶回升
        2204580  => (SubProfessionId.SubProfession_Frostbeam,          9), // 霜天  根から9 node=261001  射线多发寒冰弹
        2204590  => (SubProfessionId.SubProfession_Frostbeam,         10), // 霜天  根から10 node=209017  玄冰之息
        2204600  => (SubProfessionId.SubProfession_Frostbeam,          5), // 霜天  根から5 node=223026  玄冰潮汐
        2204610  => (SubProfessionId.SubProfession_Frostbeam,          8), // 霜天  根から8 node=267001  寒冰射线增伤
        2204620  => (SubProfessionId.SubProfession_Frostbeam,         14), // 霜天  根から14 node=265001  广域冰箭
        2204630  => (SubProfessionId.SubProfession_Frostbeam,          4), // 霜天  根から4 node=210017  智力冰晶
        2204640  => (SubProfessionId.SubProfession_Frostbeam,          9), // 霜天  根から9 node=264001  快速吟唱
        2204650  => (SubProfessionId.SubProfession_Frostbeam,         14), // 霜天  根から14 node=257001  冰箭锐击
        2204660  => (SubProfessionId.SubProfession_Frostbeam,          7), // 霜天  根から7 node=269001  射线精进二式
        2204670  => (SubProfessionId.SubProfession_Frostbeam,          7), // 霜天  根から7 node=270001  冰晶扩充
        2204680  => (SubProfessionId.SubProfession_Frostbeam,          9), // 霜天  根から9 node=271001  智力增幅
        2205060  => (SubProfessionId.SubProfession_Vanguard,           8), // 烈風  根から8 node=405014  刚烈之击
        2205070  => (SubProfessionId.SubProfession_Vanguard,           3), // 烈風  根から3 node=406014  异技瞬回
        2205080  => (SubProfessionId.SubProfession_Vanguard,           2), // 烈風  根から2 node=6090  快枪流星
        2205090  => (SubProfessionId.SubProfession_Vanguard,           5), // 烈風  根から5 node=409014  气劲加持
        2205100  => (SubProfessionId.SubProfession_Vanguard,           9), // 烈風  根から9 node=410014  野性之瞳
        2205110  => (SubProfessionId.SubProfession_Vanguard,           4), // 烈風  根から4 node=43048  风舞轻灵
        2205120  => (SubProfessionId.SubProfession_Vanguard,           4), // 烈風  根から4 node=35105  追风逐影
        2205130  => (SubProfessionId.SubProfession_Vanguard,          10), // 烈風  根から10 node=413014  神影螺旋
        2205140  => (SubProfessionId.SubProfession_Skyward,           10), // 乱風  根から10 node=421010  刹那暴击
        2205150  => (SubProfessionId.SubProfession_Skyward,            5), // 乱風  根から5 node=6101  飞矛贯穿
        2205160  => (SubProfessionId.SubProfession_Skyward,            2), // 乱風  根から2 node=6100  福风双修
        2205170  => (SubProfessionId.SubProfession_Skyward,            6), // 乱風  根から6 node=463001  速落身法
        2205180  => (SubProfessionId.SubProfession_Skyward,            9), // 乱風  根から9 node=419010  空舞重击
        2205190  => (SubProfessionId.SubProfession_Skyward,            4), // 乱風  根から4 node=37119  脆弱之触
        2205200  => (SubProfessionId.SubProfession_Skyward,            5), // 乱風  根から5 node=467001  龙卷之舞
        2205210  => (SubProfessionId.SubProfession_Skyward,            5), // 乱風  根から5 node=418011  天翼翻转
        2205250  => (SubProfessionId.SubProfession_Vanguard,           8), // 烈風  根から8 node=428022  怒火长矛
        2205290  => (SubProfessionId.SubProfession_Skyward,            0), // 乱風  根から0 node=432008  翔反
        2205300  => (SubProfessionId.SubProfession_Vanguard,           0), // 烈風  根から0 node=433007  玄武背击
        2205320  => (SubProfessionId.SubProfession_Skyward,            8), // 乱風  根から8 node=423011  神风之助
        2205370  => (SubProfessionId.SubProfession_Vanguard,           2), // 烈風  根から2 node=442001  破追精进
        2205380  => (SubProfessionId.SubProfession_Vanguard,           6), // 烈風  根から6 node=447001  刚勇
        2205390  => (SubProfessionId.SubProfession_Vanguard,           5), // 烈風  根から5 node=6096  气劲加持
        2205400  => (SubProfessionId.SubProfession_Vanguard,           5), // 烈風  根から5 node=6091  无畏疾风
        2205410  => (SubProfessionId.SubProfession_Vanguard,           8), // 烈風  根から8 node=454001  微风低语
        2205420  => (SubProfessionId.SubProfession_Vanguard,           6), // 烈風  根から6 node=1503  疾驰龙炮
        2205430  => (SubProfessionId.SubProfession_Vanguard,           8), // 烈風  根から8 node=446001  千疮百孔
        2205440  => (SubProfessionId.SubProfession_Vanguard,           6), // 烈風  根から6 node=453001  螺旋撕裂
        2205450  => (SubProfessionId.SubProfession_Vanguard,          12), // 烈風  根から12 node=444002  刚毅
        2205460  => (SubProfessionId.SubProfession_Vanguard,           2), // 烈風  根から2 node=452001  微风迅捷
        2205470  => (SubProfessionId.SubProfession_Vanguard,           8), // 烈風  根から8 node=412015  风元素之息
        2205480  => (SubProfessionId.SubProfession_Vanguard,          12), // 烈風  根から12 node=445001  风起
        2205490  => (SubProfessionId.SubProfession_Vanguard,           3), // 烈風  根から3 node=411014  强攻
        2205500  => (SubProfessionId.SubProfession_Vanguard,          12), // 烈風  根から12 node=448001  螺旋爆炎
        2205510  => (SubProfessionId.SubProfession_Vanguard,          12), // 烈風  根から12 node=440001  龙之怒焰
        2205520  => (SubProfessionId.SubProfession_Vanguard,          10), // 烈風  根から10 node=407014  风环龙炮
        2205530  => (SubProfessionId.SubProfession_Skyward,            2), // 乱風  根から2 node=456001  飞鸟精进
        2205540  => (SubProfessionId.SubProfession_Skyward,            8), // 乱風  根から8 node=420010  锐利精进
        2205550  => (SubProfessionId.SubProfession_Skyward,            8), // 乱風  根から8 node=414010  长矛回复
        2205560  => (SubProfessionId.SubProfession_Skyward,            6), // 乱風  根から6 node=1504  锐利长息
        2205570  => (SubProfessionId.SubProfession_Skyward,            4), // 乱風  根から4 node=33057  锐利扩充
        2205580  => (SubProfessionId.SubProfession_Skyward,            2), // 乱風  根から2 node=460001  锐利翔返
        2205590  => (SubProfessionId.SubProfession_Skyward,           12), // 乱風  根から12 node=468001  追击之力
        2205600  => (SubProfessionId.SubProfession_Skyward,            6), // 乱風  根から6 node=466001  卓绝风华
        2205610  => (SubProfessionId.SubProfession_Skyward,           12), // 乱風  根から12 node=469001  风神·锐利冲击
        2205620  => (SubProfessionId.SubProfession_Skyward,            3), // 乱風  根から3 node=417010  刹那破式
        2205630  => (SubProfessionId.SubProfession_Skyward,            8), // 乱風  根から8 node=464001  风卷劲击
        2205640  => (SubProfessionId.SubProfession_Skyward,           10), // 乱風  根から10 node=422010  追击之锐
        2205650  => (SubProfessionId.SubProfession_Skyward,           12), // 乱風  根から12 node=457001  刹那追击
        2205660  => (SubProfessionId.SubProfession_Skyward,           12), // 乱風  根から12 node=470001  破式
        2205670  => (SubProfessionId.SubProfession_Skyward,            5), // 乱風  根から5 node=6104  锐利回响
        2205680  => (SubProfessionId.SubProfession_Skyward,            3), // 乱風  根から3 node=416010  神风幸运
        2206090  => (SubProfessionId.SubProfession_Recovery,           0), // 光砕  根から0 node=1208009  盾击流
        2206100  => (SubProfessionId.SubProfession_Recovery,           3), // 光砕  根から3 node=1209009  神谕
        2206110  => (SubProfessionId.SubProfession_Recovery,          11), // 光砕  根から11 node=1246001  裁决启示
        2206120  => (SubProfessionId.SubProfession_Recovery,           3), // 光砕  根から3 node=1211009  圣环护卫
        2206130  => (SubProfessionId.SubProfession_Recovery,           3), // 光砕  根から3 node=1212009  光护
        2206140  => (SubProfessionId.SubProfession_Recovery,           8), // 光砕  根から8 node=8684  圣光守卫赞歌
        2206150  => (SubProfessionId.SubProfession_Recovery,           7), // 光砕  根から7 node=34158  无畏之盾
        2206160  => (SubProfessionId.SubProfession_Recovery,          11), // 光砕  根から11 node=1249001  圣光守卫惩戒
        2206170  => (SubProfessionId.SubProfession_Recovery,          10), // 光砕  根から10 node=1216009  光明圣剑
        2206190  => (SubProfessionId.SubProfession_Shield,             0), // 光盾  根から0 node=1218011  屏障流
        2206200  => (SubProfessionId.SubProfession_Shield,             7), // 光盾  根から7 node=34160  光障
        2206210  => (SubProfessionId.SubProfession_Shield,             8), // 光盾  根から8 node=8688  光铸屏障的升华
        2206220  => (SubProfessionId.SubProfession_Shield,             3), // 光盾  根から3 node=1221011  圣环咏叹
        2206230  => (SubProfessionId.SubProfession_Shield,             6), // 光盾  根から6 node=1222008  圣击
        2206240  => (SubProfessionId.SubProfession_Shield,             3), // 光盾  根から3 node=8687  神圣光辉
        2206250  => (SubProfessionId.SubProfession_Shield,            10), // 光盾  根から10 node=1258001  决心斩击
        2206260  => (SubProfessionId.SubProfession_Shield,             6), // 光盾  根から6 node=1224008  光铸驱动
        2206270  => (SubProfessionId.SubProfession_Shield,             9), // 光盾  根から9 node=1226008  冷酷回溯
        2206290  => (SubProfessionId.SubProfession_Shield,            10), // 光盾  根から10 node=1255001  众生裁决
        2206360  => (SubProfessionId.SubProfession_Recovery,           7), // 光砕  根から7 node=40076  剑舞
        2206370  => (SubProfessionId.SubProfession_Recovery,           6), // 光砕  根から6 node=1210009  持盾冲击
        2206380  => (SubProfessionId.SubProfession_Recovery,           6), // 光砕  根から6 node=1215009  清算炎盾
        2206390  => (SubProfessionId.SubProfession_Recovery,           3), // 光砕  根から3 node=6457  圣光时效
        2206400  => (SubProfessionId.SubProfession_Recovery,           8), // 光砕  根から8 node=1602  圣光召唤
        2206410  => (SubProfessionId.SubProfession_Recovery,           9), // 光砕  根から9 node=1213009  光击连锁
        2206420  => (SubProfessionId.SubProfession_Recovery,           5), // 光砕  根から5 node=1239001  清算爆炎
        2206430  => (SubProfessionId.SubProfession_Recovery,           9), // 光砕  根から9 node=1240001  圣体治愈
        2206440  => (SubProfessionId.SubProfession_Recovery,           9), // 光砕  根から9 node=1243001  光元素加护
        2206450  => (SubProfessionId.SubProfession_Recovery,           8), // 光砕  根から8 node=1244001  守护极意
        2206460  => (SubProfessionId.SubProfession_Recovery,           7), // 光砕  根から7 node=1245001  盾击守护
        2206470  => (SubProfessionId.SubProfession_Recovery,           3), // 光砕  根から3 node=8682  光愈裁断
        2206480  => (SubProfessionId.SubProfession_Recovery,           9), // 光砕  根から9 node=1214009  极意神圣之击
        2206490  => (SubProfessionId.SubProfession_Recovery,           7), // 光砕  根から7 node=1241001  盾击强化
        2206500  => (SubProfessionId.SubProfession_Shield,             7), // 光盾  根から7 node=40078  极意征伐
        2206520  => (SubProfessionId.SubProfession_Shield,             5), // 光盾  根から5 node=1260001  逆境强化
        2206530  => (SubProfessionId.SubProfession_Shield,            10), // 光盾  根から10 node=1225008  广域征伐
        2206540  => (SubProfessionId.SubProfession_Shield,             3), // 光盾  根から3 node=1220011  悍勇无畏
        2206550  => (SubProfessionId.SubProfession_Shield,             8), // 光盾  根から8 node=1607  光芒核心
        2206560  => (SubProfessionId.SubProfession_Shield,             3), // 光盾  根から3 node=1219011  征伐追击
        2206570  => (SubProfessionId.SubProfession_Shield,            11), // 光盾  根から11 node=1256001  决断之刃
        2206580  => (SubProfessionId.SubProfession_Shield,             8), // 光盾  根から8 node=1257001  冷酷加速
        2206590  => (SubProfessionId.SubProfession_Shield,            11), // 光盾  根から11 node=1254001  圣印强化
        2206600  => (SubProfessionId.SubProfession_Shield,             9), // 光盾  根から9 node=1223008  圣环守护
        2206610  => (SubProfessionId.SubProfession_Shield,             8), // 光盾  根から8 node=6463  裁决精进
        2206620  => (SubProfessionId.SubProfession_Shield,             7), // 光盾  根から7 node=1262001  圣印追击
        2206630  => (SubProfessionId.SubProfession_Shield,             5), // 光盾  根から5 node=1227013  溢愈光壁
        2206640  => (SubProfessionId.SubProfession_Shield,             9), // 光盾  根から9 node=1263001  光愈
        2206650  => (SubProfessionId.SubProfession_Shield,             9), // 光盾  根から9 node=1266001  光元素加护
        2206660  => (SubProfessionId.SubProfession_Shield,             3), // 光盾  根から3 node=6461  圣剑强化
        2206670  => (SubProfessionId.SubProfession_Recovery,           5), // 光砕  根から5 node=1227012  光晕
        2206680  => (SubProfessionId.SubProfession_Recovery,          10), // 光砕  根から10 node=1238001  众生裁决
        2207090  => (SubProfessionId.SubProfession_Dissonance,         0), // 狂音  根から0 node=1308006  近战流
        2207100  => (SubProfessionId.SubProfession_Dissonance,         5), // 狂音  根から5 node=1313006  幸运闪光
        2207110  => (SubProfessionId.SubProfession_Dissonance,         2), // 狂音  根から2 node=6558  全域展开
        2207120  => (SubProfessionId.SubProfession_Dissonance,         2), // 狂音  根から2 node=6557  断章
        2207130  => (SubProfessionId.SubProfession_Dissonance,         2), // 狂音  根から2 node=2401  音浪烈焰
        2207140  => (SubProfessionId.SubProfession_Dissonance,         5), // 狂音  根から5 node=1312006  双重旋律
        2207150  => (SubProfessionId.SubProfession_Dissonance,         6), // 狂音  根から6 node=1328012  炽焰治愈
        2207160  => (SubProfessionId.SubProfession_Dissonance,        10), // 狂音  根から10 node=1329011  强化节拍
        2207170  => (SubProfessionId.SubProfession_Dissonance,         4), // 狂音  根から4 node=1309006  重启
        2207180  => (SubProfessionId.SubProfession_Concerto,           0), // 響奏  根から0 node=1317006  远程流
        2207190  => (SubProfessionId.SubProfession_Concerto,           2), // 響奏  根から2 node=2406  华彩章节充能
        2207200  => (SubProfessionId.SubProfession_Concerto,           8), // 響奏  根から8 node=1320006  愈合倍增
        2207210  => (SubProfessionId.SubProfession_Concerto,           9), // 響奏  根から9 node=1360001  暴击治疗
        2207220  => (SubProfessionId.SubProfession_Concerto,           6), // 響奏  根から6 node=1328011  烈火节拍
        2207230  => (SubProfessionId.SubProfession_Concerto,          12), // 響奏  根から12 node=1363001  天赋占位
        2207240  => (SubProfessionId.SubProfession_Concerto,           2), // 響奏  根から2 node=6568  绚烂焰火
        2207250  => (SubProfessionId.SubProfession_Concerto,           2), // 響奏  根から2 node=6567  音域扩充
        2207260  => (SubProfessionId.SubProfession_Concerto,           6), // 響奏  根から6 node=1318006  音域扩充强化
        2207370  => (SubProfessionId.SubProfession_Dissonance,         6), // 狂音  根から6 node=1339001  不屈谐音
        2207380  => (SubProfessionId.SubProfession_Dissonance,         4), // 狂音  根から4 node=1310006  挥击回涌
        2207390  => (SubProfessionId.SubProfession_Dissonance,         4), // 狂音  根から4 node=1315006  幸运倍乘
        2207400  => (SubProfessionId.SubProfession_Dissonance,         7), // 狂音  根から7 node=1330011  律动赞歌
        2207410  => (SubProfessionId.SubProfession_Dissonance,        11), // 狂音  根から11 node=1327011  音浪展开
        2207420  => (SubProfessionId.SubProfession_Dissonance,         9), // 狂音  根から9 node=1341001  安可永续
        2207430  => (SubProfessionId.SubProfession_Dissonance,         8), // 狂音  根から8 node=1314006  炎律狂踏
        2207440  => (SubProfessionId.SubProfession_Dissonance,         8), // 狂音  根から8 node=1316006  烈焰音符
        2207450  => (SubProfessionId.SubProfession_Dissonance,        14), // 狂音  根から14 node=1347001  安可狂想
        2207460  => (SubProfessionId.SubProfession_Dissonance,         8), // 狂音  根から8 node=1311006  伟大旋律
        2207470  => (SubProfessionId.SubProfession_Dissonance,        12), // 狂音  根から12 node=1346001  天赋占位
        2207480  => (SubProfessionId.SubProfession_Dissonance,        10), // 狂音  根から10 node=1345001  安可锐击
        2207500  => (SubProfessionId.SubProfession_Dissonance,         8), // 狂音  根から8 node=1349001  极意万众瞩目
        2207510  => (SubProfessionId.SubProfession_Dissonance,        10), // 狂音  根から10 node=1350001  悠扬乐曲
        2207520  => (SubProfessionId.SubProfession_Dissonance,         6), // 狂音  根から6 node=1343001  磅礴音浪
        2207530  => (SubProfessionId.SubProfession_Concerto,           4), // 響奏  根から4 node=1325006  会心充能律
        2207540  => (SubProfessionId.SubProfession_Concerto,           6), // 響奏  根から6 node=1356001  音塔爆炎冲击
        2207550  => (SubProfessionId.SubProfession_Concerto,          11), // 響奏  根から11 node=1359001  多目标热力增幅
        2207560  => (SubProfessionId.SubProfession_Concerto,           5), // 響奏  根から5 node=1323006  热烈音塔爆炎冲击
        2207570  => (SubProfessionId.SubProfession_Concerto,           5), // 響奏  根から5 node=1326011  爆裂节奏
        2207580  => (SubProfessionId.SubProfession_Concerto,           8), // 響奏  根から8 node=1321006  扩音效能
        2207590  => (SubProfessionId.SubProfession_Concerto,           5), // 響奏  根から5 node=1351006  渐强治愈和弦
        2207600  => (SubProfessionId.SubProfession_Concerto,           4), // 響奏  根から4 node=1353001  暴击天秤
        2207610  => (SubProfessionId.SubProfession_Concerto,          10), // 響奏  根から10 node=1324006  鸣奏交响式
        2207620  => (SubProfessionId.SubProfession_Concerto,           7), // 響奏  根から7 node=1361001  活力贮藏
        2207630  => (SubProfessionId.SubProfession_Concerto,          14), // 響奏  根から14 node=1362001  安可赞歌
        2207640  => (SubProfessionId.SubProfession_Concerto,           8), // 響奏  根から8 node=1352001  宏伟旋律
        2207650  => (SubProfessionId.SubProfession_Concerto,          10), // 響奏  根から10 node=1329012  音域深化
        2207660  => (SubProfessionId.SubProfession_Concerto,           8), // 響奏  根から8 node=1327012  极意万众瞩目
        2207680  => (SubProfessionId.SubProfession_Concerto,          10), // 響奏  根から10 node=1357001  螺旋炎奏
        2208130  => (SubProfessionId.SubProfession_FormlessExpertise,  0), // 双炎  根から0 node=312005  塔塔Rank判定
        2208140  => (SubProfessionId.SubProfession_FormlessExpertise,  2), // 双炎  根から2 node=313005  炽热之契
        2208150  => (SubProfessionId.SubProfession_FormlessExpertise,  4), // 双炎  根から4 node=314005  监控荒川之寂灭添加/rank提升
        2208160  => (SubProfessionId.SubProfession_FormlessExpertise,  4), // 双炎  根から4 node=315005  无相减少指定技能组CD最长的技能CD
        2208170  => (SubProfessionId.SubProfession_FormlessExpertise,  6), // 双炎  根から6 node=316005  炽炎状态专精技能加引燃
        2208180  => (SubProfessionId.SubProfession_FormlessExpertise,  7), // 双炎  根から7 node=317005  引燃叠层概率计数
        2208190  => (SubProfessionId.SubProfession_FormlessExpertise,  9), // 双炎  根から9 node=318005  炼狱火车可以幸运一击，伤害增加
        2208200  => (SubProfessionId.SubProfession_FormlessExpertise,  4), // 双炎  根から4 node=319005  炽焰突袭减CD
        2208210  => (SubProfessionId.SubProfession_FormlessExpertise,  6), // 双炎  根から6 node=320005  时轮幸魂
        2208220  => (SubProfessionId.SubProfession_FormlessExpertise,  8), // 双炎  根から8 node=321005  时轮敏魂
        2208230  => (SubProfessionId.SubProfession_FormlessExpertise,  6), // 双炎  根から6 node=322005  炽焰突袭回复损失炎魂
        2208240  => (SubProfessionId.SubProfession_FormlessExpertise,  5), // 双炎  根から5 node=323005  旋风斩命中目标加燃烧
        2208250  => (SubProfessionId.SubProfession_FormlessExpertise, 11), // 双炎  根から11 node=324005  暴怒劈斩加地火流星
        2208260  => (SubProfessionId.SubProfession_FormlessExpertise, 10), // 双炎  根から10 node=325005  无上战域
        2208280  => (SubProfessionId.SubProfession_FormlessExpertise, 12), // 双炎  根から12 node=327005  三刀流成功判定
        2208290  => (SubProfessionId.SubProfession_FormlessExpertise,  4), // 双炎  根から4 node=328005  精通转三刀流概率
        2208300  => (SubProfessionId.SubProfession_FormlessExpertise,  9), // 双炎  根から9 node=329005  连打无相
        2208310  => (SubProfessionId.SubProfession_FormlessExpertise,  6), // 双炎  根から6 node=330005  三刀流触发忽视物理防御
        2208320  => (SubProfessionId.SubProfession_FormlessExpertise, 10), // 双炎  根から10 node=331005  三刀流触发幸运一击概率
        2208330  => (SubProfessionId.SubProfession_FormlessExpertise, 10), // 双炎  根から10 node=332005  三刀流触发属性增伤
        2208340  => (SubProfessionId.SubProfession_FormlessExpertise,  2), // 双炎  根から2 node=333005  普攻特攻三刀判定
        2208350  => (SubProfessionId.SubProfession_FormlessExpertise, 11), // 双炎  根から11 node=334005  鸿运连刃
        2208360  => (SubProfessionId.SubProfession_FormlessExpertise,  8), // 双炎  根から8 node=335005  根据rank等级为三刀流增伤
        2208370  => (SubProfessionId.SubProfession_FormlessExpertise,  9), // 双炎  根から9 node=336005  寂灭业火
        2208380  => (SubProfessionId.SubProfession_FormlessExpertise, 12), // 双炎  根から12 node=337005  rank提升减少荒川之寂灭CD
        2208430  => (SubProfessionId.SubProfession_CrimsonExpertise,   0), // 炎舞  根から0 node=342005  狂战池子积攒
        2208440  => (SubProfessionId.SubProfession_CrimsonExpertise,   4), // 炎舞  根から4 node=343005  魂焰
        2208450  => (SubProfessionId.SubProfession_CrimsonExpertise,   4), // 炎舞  根から4 node=344005  怒焰狂锐之一
        2208460  => (SubProfessionId.SubProfession_CrimsonExpertise,   7), // 炎舞  根から7 node=345005  赤红之地·炎魂
        2208470  => (SubProfessionId.SubProfession_CrimsonExpertise,   6), // 炎舞  根から6 node=346005  赤红之地·迅捷
        2208480  => (SubProfessionId.SubProfession_CrimsonExpertise,   2), // 炎舞  根から2 node=359005  强化无羁坠星
        2208490  => (SubProfessionId.SubProfession_CrimsonExpertise,   2), // 炎舞  根から2 node=348005  怒焰狂锐之二
        2208500  => (SubProfessionId.SubProfession_CrimsonExpertise,   7), // 炎舞  根から7 node=349005  赤红之地的坠星二式
        2208510  => (SubProfessionId.SubProfession_CrimsonExpertise,  10), // 炎舞  根から10 node=350005  消耗炎魂/赤痕回复无羁和强化无羁CD
        2208520  => (SubProfessionId.SubProfession_CrimsonExpertise,   6), // 炎舞  根から6 node=351005  赤红破斩
        2208530  => (SubProfessionId.SubProfession_CrimsonExpertise,   7), // 炎舞  根から7 node=352005  炎魔显现
        2208540  => (SubProfessionId.SubProfession_CrimsonExpertise,   5), // 炎舞  根から5 node=353005  赤红专注
        2208550  => (SubProfessionId.SubProfession_CrimsonExpertise,   8), // 炎舞  根から8 node=354005  流川如华斩充能
        2208560  => (SubProfessionId.SubProfession_CrimsonExpertise,   2), // 炎舞  根から2 node=355005  特攻刷新免费流川如华斩
        2208570  => (SubProfessionId.SubProfession_CrimsonExpertise,  12), // 炎舞  根から12 node=356005  无尽之炎魔加满业火，且期间不删除业火
        2208580  => (SubProfessionId.SubProfession_CrimsonExpertise,   6), // 炎舞  根から6 node=357005  赤红暴击
        2208590  => (SubProfessionId.SubProfession_CrimsonExpertise,   4), // 炎舞  根から4 node=358005  赤红贯穿
        2208600  => (SubProfessionId.SubProfession_CrimsonExpertise,   4), // 炎舞  根から4 node=347006  强化炎魔天落杀
        2208610  => (SubProfessionId.SubProfession_CrimsonExpertise,  10), // 炎舞  根から10 node=360005  猩红之悟
        2208620  => (SubProfessionId.SubProfession_CrimsonExpertise,   8), // 炎舞  根から8 node=361005  迷狂炎舞派生
        2208630  => (SubProfessionId.SubProfession_CrimsonExpertise,  12), // 炎舞  根から12 node=362005  迷狂炎舞三刀流判定
        2208640  => (SubProfessionId.SubProfession_CrimsonExpertise,  10), // 炎舞  根から10 node=363005  迷狂炎舞段数判定
        // 2208650 大红莲丸触发逻辑(node=364005) は除外。丸めで同じ扱いになる 2208652 大红莲丸派生 が
        // 因子(シーズンタレント) 3060430「真实因子-触发大红莲丸，增伤buff」からも出るため。
        // 因子はID帯 3050000〜3060999 で、系列 3060 = 赤焰。ワイヤでは fightSourceType=13 SeasonTalent。
        // タレントではないので判定表のキーにできず、親優先(TryResolveSpecByParentBuff)でも解けない。
        //
        // 常設の SpecConflictProbe が 2026-09-12 に実戦で検知した:
        //   観測ID=2208652 ftype=1 src=3060430 → 丸め 2208650 → 炎舞
        //   だが控えマーカーは 2208130(双炎)。因子だけ着けた双炎の人が炎舞にされる。
        //
        // 本物の炎舞では 2208650(ftype=6) → 2208651 大红莲丸计数 → 2208652 と繋がる。
        // 過去ログでこの帯を出した7人は全員 炎舞マーカー 2208430 を持っており、
        // このキーでしか判定できなかった人は0人(同じ人には兄弟キー 2208640 も当たっている)。
        // 外しても失うものが無い。
        //
        // 再生成しても復活させないこと。
        2208660  => (SubProfessionId.SubProfession_CrimsonExpertise,   9), // 炎舞  根から9 node=365005  炎舞的急速奥义
        2208670  => (SubProfessionId.SubProfession_CrimsonExpertise,   6), // 炎舞  根から6 node=366005  怒焰奥义
        _ => (SubProfessionId.SubProfession_Unknown, -1)
    };

    /// <summary>
    /// 観測したバフIDから特化を引く。
    ///
    /// <para>
    /// バフIDは <c>系統×100 + レベル</c> の形で、タレントが付与するのは必ずレベルが10の倍数のもの。
    /// 実行時に乗るのはその <c>+1</c> <c>+2</c> … の変種なので、10刻みに丸めてから引く。
    /// 付与バフ %d 件はすべて末尾0で、+1〜+9 に別の<b>付与</b>バフは1件も無いことを確認済み。
    /// </para>
    ///
    /// <para>
    /// <b>ただし「変種は元のバフに属する」は成り立たないことがある。</b> +1〜+9 に入るのは
    /// 付与バフだけではなく、<b>別ツリーの下流の効果バフ</b>が落ちてくる。実測で
    /// <c>2208281 刀数判定</c>(双炎の丸め先に落ちるが炎舞からも出る)と
    /// <c>2206261 裁决</c>(光盾の丸め先に落ちるが光砕からしか出ない)の2件。
    /// <b>そのため呼び出し側は <see cref="TryResolveSpecByParentBuff"/> を併せて呼び、
    /// 変種のときは親で特化を引き直すこと。</b>
    /// </para>
    ///
    /// <para>
    /// 検証のため <paramref name="grantedBuffId"/> を返すので、呼び出し側で観測値と一緒に記録すること。
    /// </para>
    /// </summary>
    /// <param name="distanceFromRoot">
    /// このバフを付与するノードの、根ノードからの最短距離。
    /// 根＝特化アビリティなので、距離が小さいほど「タレントを最小限しか振っていない人」でも当たる。
    /// 実際に振る量は人によるため、当たった距離を記録して最小投資でも届くかを見る。
    /// </param>
    public static bool TryResolveSpecTalentBuff(
        int observedBuffId,
        out int grantedBuffId,
        out SubProfessionId spec,
        out int distanceFromRoot)
    {
        grantedBuffId = 0;
        spec = SubProfessionId.SubProfession_Unknown;
        distanceFromRoot = -1;
        if (observedBuffId <= 0)
        {
            return false;
        }

        var floored = observedBuffId - (observedBuffId % 10);
        var (resolved, distance) = LookupGrantedTreeBuff(floored);
        if (resolved == SubProfessionId.SubProfession_Unknown)
        {
            return false;
        }

        grantedBuffId = floored;
        spec = resolved;
        distanceFromRoot = distance;
        return true;
    }

    /// <summary>
    /// 変種バフ(+1〜+9)の特化を、<b>ワイヤが名乗る親</b>で引き直す。引けたときだけ true。
    ///
    /// <para>
    /// 10刻み丸めは「変種は元のバフに属する」という推定でしかない。実際には
    /// <b>別ツリーの下流効果が、隣の特化の付与バフの丸め範囲に落ちる</b>ことがある。
    /// </para>
    ///
    /// <list type="bullet">
    ///   <item>
    ///     <c>2208281 刀数判定</c> — 双炎の <c>2208280</c>/<c>2208340</c> と
    ///     <b>炎舞の <c>2208630</c></b> の3つが同じものを出す(ゲーム内タレント名は3つとも
    ///     「イラプション」の派生)。丸めると炎舞の分まで双炎になる。
    ///   </item>
    ///   <item>
    ///     <c>2206261 裁决</c> — 親は<b>光砕の <c>2206110</c>(審判)</b> だけなのに、
    ///     丸めると<b>光盾の <c>2206260</c>(光駆動)</b> になる。名前も効果も無関係で、
    ///     IDが隣接しているだけ。
    ///   </item>
    /// </list>
    ///
    /// <para>
    /// 実測(ログ188本)を実行時と同じ条件(そのイベント時点の控えマーカー / 距離0は対象外)で
    /// 数えると、丸めだけでは<b>202件が出し手のマーカーと食い違い</b>、
    /// 親を優先すると<b>0件</b>になる。正しかったものが誤りに変わった回も<b>0件</b>。
    /// </para>
    ///
    /// <para>
    /// <b>丸めの置き換えではない。</b> 変種168,987件のうち親が引けるのは26,269件だけで、
    /// 丸めをやめると特化が一度も付かない出し手が921人中438人になる。
    /// これは「引けたときだけ丸めを上書きする」もの。
    /// </para>
    ///
    /// <para>
    /// <b>親を見るのは変種のときだけ。</b> 観測IDそのものが表のキー(末尾0)なら丸めは厳密で、
    /// そこへ推定を挟む理由がない。実測でも「観測IDが表のキーなのに親が別特化を指した回」は0件。
    /// </para>
    ///
    /// <para>
    /// <b>返すのは特化だけ。</b> 距離やマーカー判定に使ってはいけない —
    /// 親がマーカー本体のことがあり(<c>2203291</c> の親は鷹弓の根 <c>2203290</c>)、
    /// 親の距離0を採ると派生バフでマーカーを latch してしまう。
    /// </para>
    /// </summary>
    /// <param name="fightSourceType">
    /// <c>FightSourceInfo.FightSourceType</c>。親を名乗るのは <c>Buff(1)</c> のときだけで、
    /// ツリー一括配信(<c>Talent(6)</c>)は <c>sourceConfigId=0</c> で来る。
    /// </param>
    public static bool TryResolveSpecByParentBuff(
        int observedBuffId,
        int fightSourceType,
        int sourceConfigId,
        out SubProfessionId spec,
        out int parentBuffId)
    {
        spec = SubProfessionId.SubProfession_Unknown;
        parentBuffId = 0;

        if (fightSourceType != (int)EFightSource.Buff || sourceConfigId <= 0 || observedBuffId <= 0)
        {
            return false;
        }

        // 観測IDそのものが表のキーなら丸めは厳密。推定を挟まない。
        if (LookupGrantedTreeBuff(observedBuffId).Spec != SubProfessionId.SubProfession_Unknown)
        {
            return false;
        }

        // 親も変種で届くので丸めてから引く。全ログ再生で、丸めた親が引けるようになるのは
        // 122,079件あり、そのうち観測IDの丸めと答えが変わるのは0件だった。
        var floored = sourceConfigId - (sourceConfigId % 10);
        var (resolved, _) = LookupGrantedTreeBuff(floored);
        if (resolved == SubProfessionId.SubProfession_Unknown)
        {
            return false;
        }

        spec = resolved;
        parentBuffId = floored;
        return true;
    }
}
